# Configuraci\u00f3n de la aplicaci\u00f3n
app.base.url=https://8684-2806-104e-16-b7ce-893f-be32-5deb-2398.ngrok-free.app
app.login.endpoint=/DatabaseService/api/auth/login
app.service.endpoint=/DatabaseService/api/service
app.token.header=Authorization

# Configuraci\u00f3n del file server
app.fileserver.url=https://apigateway.nicepebble-44974112.eastus.azurecontainerapps.io/files/upload
app.fileserver.token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcm92ZWVkb3JlczIiLCJyb2xlIjoiQURNSU4iLCJpZCI6IjY3ZWI0MmUzZjc2NDI1NGNiYWVhZDk0OCIsImNvbXBhbnkiOiJwcm92ZWVkb3JlczIiLCJpYXQiOjE3NDYwNjY3NzcsImV4cCI6MTc0NjE1MzE3N30.QXyEG7YyjF9nz2HEGg04Ih8FuYEcmWb9CpGr_WciNQ0

# Nuevas credenciales para autenticaci\u00f3n autom\u00e1tica
app.api.auth.correo=proveedor2@gmail.com
app.api.auth.password=123456

